### ISSUE TITLE
Regex comparison is not escaping special characters before attempting to match

### ISSUE THREAD

**Issue by jcornell** [mrak/stubby4net#14]
When setting up a request with post data that has an array of objects of type X, where X has a property of type Guid - Regex matching throws an exception as hyphens in the data are not escaped.

```
[Test]
        public void Find_ShouldRetrieveEndpoint_WhenPostDataWithAnArrayOfGuidsMatch()
        {
            var myObject = new[] {new {Id = Guid.NewGuid()}, new {Id = Guid.NewGuid()}};
            var myObjectSerialized = new JavaScriptSerializer().Serialize(myObject);
            var inserted = new Endpoint
            {
                Request = new Request {Url = "/phantom", Method = new List<string> {"POST"}, Post = myObjectSerialized}
            };
            var incoming = new Endpoint
            {
                Request = new Request {Url = "/phantom", Method = new List<string> {"POST"}, Post = myObjectSerialized}
            };

            _endpointDb.Insert(inserted);
            var actual = _endpointDb.Find(incoming);

            Assert.NotNull(actual);
        }
```

In an effort to track down the offending code, I was able to make this test pass by changing the Request.Matches method from `if(Post != null && !Regex.IsMatch(other.Post, Post))` to `if(Post != null && !Regex.IsMatch(other.Post, Regex.Escape(Post)))`

**Comment by mrak** [comment]
That is the intended behavior. Stubby will attempt to treat the configuration data as a regular expression and fall back to string matching if it isn't a valid regex.

It looks as if you already found the solution: escape your `Post` string prior to creating an `Endpoint` if you want it to be treating as a string literal.

**Comment by jcornell** [comment]
Okay thanks Eric.
